# --- !Ups
drop table if exists "TRANSACTIONS";

create table IF NOT EXISTS "TRANSACTIONS" (
  "ID" bigint generated by default as identity(start with 1) not null primary key,
  "SYMBOL" varchar,
  "ACTION" varchar not null,
  "QUANTITY" NUMERIC(10,3),
  "PRICE" NUMERIC(10,3),
  "AMOUNT" NUMERIC(10,3) not null,
  "DATE" DATE not null,
  "COMMISSION" NUMERIC(10,3) not null,
  "DESCRIPTION" varchar,
  "ACCOUNT_TYPE" varchar not null,
  "OWNER" varchar not null
);