# --- !Ups

create table "people" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "name" varchar not null,
  "age" int not null
);

create table IF NOT EXISTS "TRANSACTIONS" (
  "ID" bigint generated by default as identity(start with 1) not null primary key,
  "SYMBOL" varchar,
  "ACTION" varchar,
  "QUANTITY" bigint,
  "PRICE" bigint,
  "DATE" date,
  "AMOUNT" bigint,
  "COMMISSION" bigint,
  "FEE" bigint,
  "SECURITY_TYPE" varchar,
  "ACCURED_INTEREST" bigint,
  "SETTLEMENT_DATE" date,
  "DESCRIPTION" varchar
);

# --- !Downs

drop table "people" if exists;
drop table "TRANSACTIONS" if exists ;