# --- !Ups

create table "people" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "name" varchar not null,
  "age" int not null
);

create table "TRANSACTIONS" (
  "ID" bigint generated by default as identity(start with 1) not null primary key,
  "TICKER" varchar not null,
  "NUM_SHARES" varchar,
  "ACTION" varchar
);

-- def amount : Option[Double]
--   def action : String
--   def date : Option[LocalDate]
--   def ticker: String;
--   def numShares: Option[Double]

# --- !Downs

drop table "people" if exists;
